/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task10_dev;

import org.hibernate.Session;
import task10_dev.CRUDService.ClientCrudService;
import task10_dev.CRUDService.PlanetCrudService;
import task10_dev.CRUDService.TicketCrudService;
import task10_dev.DataBase.DataBase;
import task10_dev.DbServises.DatabaseInitService;
import task10_dev.Entity.Client;
import task10_dev.Entity.Planet;
import task10_dev.hibernate.HibernateUtil;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

public class App {


    public static void main(String[] args) {
        DataBase dataBase = DataBase.getInstance();
        HibernateUtil util = HibernateUtil.getINSTANCE();
        Session session = util.getSessionFactory().openSession();

       // new DatabaseInitService().initDb(dataBase);

        new TicketCrudService().createNewTicket("EAR", "MARS",1L);

    }
}
